<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>باشگاه</title>
    <link href="css/main.css" type="text/css" rel="stylesheet">
</head>

<body>

<div class="header_menu">
    <div>
        <a href="index.php">
            <div>
                صفحه نخست
            </div>
        </a>

        <div>دوره ها &nbsp;
            <i class="fa-solid fa-chalkboard-user" style="color: #000000;"></i>
        </div>
        <div>مقالات &nbsp;
            <i class="fa-solid fa-book" style="color: #000000;"></i>
        </div>
        <div id="btn_call">تماس با ما &nbsp;
            <i class="fa-solid fa-phone-volume" style="color: #000000;"></i>
        </div>
    </div>
    <div style="width: 20%;">
        <div style="float: left; font-size: 10pt" id="btn_login"> ورود/ثبت نام
            <i class="fa-solid fa-arrow-right-to-bracket fa-lg" style="color: #000000;"></i>
        </div>
    </div>
    <span style="position: absolute; height: 50px; top: 18px; right: 48%">
        <i class="fa-sharp fa-regular fa-dumbbell fa-2xl" style="color: #000000;"></i>
    </span>
</div>

<script src="js/main.js"></script>
</body>


</html>
