<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>باشگاه</title>
    <link href="css/main.css" type="text/css" rel="stylesheet">
</head>

<body>

<div class="footer_menu" id="main_footer" style="transition: 0.5s">
    <div style="width: 100%; height: 60px; text-align: center;margin: 0px;
     margin-top: 20px; font-family: 'B Nazanin';font-size: 30pt; background-color: rgba(80,80,80,1);" id="call">
        تماس با ما
    </div>
    <div style="direction: ltr">
        <i class="fa-sharp fa-solid fa-fade fa-envelope fa-2xl" style="color: #e6e6e6;"></i>
        <br>
        email:
        <br>
        address@gmail.com

    </div>
    <div>
        <i class="fa-brands fa-telegram fa-fade fa-2xl" style="color: #ffffff;"></i>
        <br>
        @address
    </div>
    <div>
        <i class="fa-brands fa-instagram fa-beat-fade fa-2xl" style="color: #fcfcfc;"></i>
        <br>
        @address
    </div>
    <div>
        <i class="fa-brands fa-twitter fa-beat-fade fa-2xl" style="color: #ffffff;"></i>
        <br>
        @address
    </div>
</div>

<script src="js/main.js"></script>
</body>


</html>

