<!DOCTYPE html>
<html lang="fa" dir="rtl">
<head>
    <meta charset="UTF-8">
    <title>باشگاه</title>
    <link href="css/main.css" type="text/css" rel="stylesheet">
    <link href="css/manager.css" type="text/css" rel="stylesheet">
</head>

<body>

<div class="header_menu">
    <div>
        <div class="menu_manager">
            <a>
                <div>
                    <i class="fa-solid fa-bars fa-sm" style="color: #000000;"></i>
                    &nbsp;منو
                </div>
            </a>

            <ul id="menu_manager">
                <li>
                    <i class="fa-solid fa-person-walking fa-lg" style="color: #000000;"></i>
                    &nbsp; برنامه تمرینی
                </li>
                <a href="">
                    <li>
                        <i class="fa-solid fa-utensils fa-lg" style="color: #000000;"></i>
                        &nbsp; برنامه غذایی
                    </li>
                </a>
                <a>
                    <li>
                        <i class="fa-sharp fa-solid fa-file-lines fa-xl" style="color: #000000;"></i>
                        &nbsp; ثبت گزارش
                    </li>
                </a>
                <a href="">
                    <li>
                        <i class="fa-solid fa-envelope fa-lg" style="color: #000000;"></i>
                        &nbsp;ارتباط با مربی
                    </li>
                </a>
            </ul>
        </div>

        <div>ورود &nbsp;
            <i class="fa-solid fa-arrow-right-to-bracket fa-lg" style="color: #000000;"></i>
        </div>
        <div>ورود &nbsp;
            <i class="fa-solid fa-arrow-right-to-bracket fa-lg" style="color: #000000;"></i>
        </div>
        <div id="btn_call">تماس با ما &nbsp;
            <i class="fa-solid fa-phone-volume" style="color: #000000;"></i>
        </div>
    </div>
    <div style="width: 20%;" class="menu_person">
        <div style="float: left; font-size: 10pt; width: 130px" id="btn_person"> نام و نام خانوادگی
            <i class="fa-solid fa-circle-user fa-lg" style="color: #000000;font-size: 20pt;margin-left: 1px;"></i>
        </div>
        <ul id="menu_person">
            <li>
                پروفایل
            </li>
            <li>
                خروج
            </li>
        </ul>
    </div>
    <span style="position: absolute; height: 50px; top: 18px; right: 48%">
        <i class="fa-sharp fa-regular fa-dumbbell fa-2xl" style="color: #000000;"></i>
    </span>
</div>

<script src="js/main.js"></script>
</body>


</html>

